version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: magicvial-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - magicvial-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: magicvial-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/magicvial
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=devSecretKeyChangeInProduction
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    depends_on:
      - postgres
      - redis
    networks:
      - magicvial-network

  postgres:
    image: postgres:16
    container_name: magicvial-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=magicvial
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - magicvial-network

  redis:
    image: redis:7
    container_name: magicvial-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - magicvial-network

  localnet:
    image: solanalabs/solana:stable
    container_name: magicvial-solana-localnet
    entrypoint: /bin/bash -c "solana-test-validator --log"
    ports:
      - "8899:8899"
      - "8900:8900"
    networks:
      - magicvial-network

  nginx:
    image: nginx:alpine
    container_name: magicvial-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - magicvial-network

volumes:
  postgres_data:
  redis_data:

networks:
  magicvial-network:
    driver: bridge 